"""EIP-712 definitions for every Avantis v2 intent.

Mirrored verbatim from `avantis-contracts-v2/src/library/SignatureHelpers.sol`
via `avantis-tx-builder/src/chain/eip712.ts`, and validated against the
golden-vector suite (tests/test_golden_vectors.py) generated by the real
on-chain hashing library.

DO NOT "normalize" field names: the contracts mix `_`-prefixed and plain names
between (and within!) structs. Any drift breaks signature recovery.

Signing quirks:
- All `deadline`/`_deadline` fields are unix MILLISECONDS.
- `TpSlReq` has NO deadline; freshness comes from `signTimestamp` (ms).
- `DelegateReq` hashes a fixed ToS constant in the `tnc` slot; standard
  signTypedData is correct as long as the message carries TNC_STRING exactly.
- `DelegateReq` ABI encoding order (expiry, tnc, deadline) differs from the
  typed-data order (expiry, deadline, tnc).
"""

from __future__ import annotations

TNC_STRING = (
    "I accept the Avantis Terms of Service: https://www.avantisfi.com/docs/tos."
    "I confirm that I am not a resident of any of the following countries/regions: "
    "Belarus, Cuba, Iran, North Korea, Russia, Syria, Crimea, United Kingdom, "
    "United States of America."
)

Field = dict[str, str]

_TRADE_TYPE: list[Field] = [
    {"name": "trader", "type": "address"},
    {"name": "pairIndex", "type": "uint256"},
    {"name": "index", "type": "uint256"},
    {"name": "initialPosToken", "type": "uint256"},
    {"name": "positionSizeUSDC", "type": "uint256"},
    {"name": "openPrice", "type": "uint256"},
    {"name": "buy", "type": "bool"},
    {"name": "leverage", "type": "uint256"},
    {"name": "tp", "type": "uint256"},
    {"name": "sl", "type": "uint256"},
    {"name": "timestamp", "type": "uint256"},
]

_UPDATE_POSITION_SIZE_TYPE: list[Field] = [
    {"name": "trader", "type": "address"},
    {"name": "pairIndex", "type": "uint256"},
    {"name": "index", "type": "uint256"},
    {"name": "openPrice", "type": "uint256"},
    {"name": "initialPosToken", "type": "uint256"},
    {"name": "leverage", "type": "uint256"},
]

INTENT_TYPES: dict[str, dict[str, list[Field]]] = {
    "OpenTradeReq": {
        "OpenTradeReq": [
            {"name": "_t", "type": "Trade"},
            {"name": "_type", "type": "uint8"},
            {"name": "_slippageP", "type": "uint256"},
            {"name": "_deadline", "type": "uint256"},
            {"name": "_nonce", "type": "uint256"},
        ],
        "Trade": _TRADE_TYPE,
    },
    "OpenTradeCoinExposureReq": {
        "OpenTradeCoinExposureReq": [
            {"name": "_t", "type": "Trade"},
            {"name": "_type", "type": "uint8"},
            {"name": "_coinExposure", "type": "uint256"},
            {"name": "_minLeverage", "type": "uint256"},
            {"name": "_maxLeverage", "type": "uint256"},
            {"name": "_slippageP", "type": "uint256"},
            {"name": "_deadline", "type": "uint256"},
            {"name": "_nonce", "type": "uint256"},
        ],
        "Trade": _TRADE_TYPE,
    },
    "CloseTradeReq": {
        "CloseTradeReq": [
            {"name": "_trader", "type": "address"},
            {"name": "_pairIndex", "type": "uint256"},
            {"name": "_index", "type": "uint256"},
            {"name": "_openTimestamp", "type": "uint256"},
            {"name": "_amount", "type": "uint256"},
            {"name": "_wantedPrice", "type": "uint256"},
            {"name": "_deadline", "type": "uint256"},
            {"name": "_nonce", "type": "uint256"},
        ],
    },
    "CloseTradeCoinExposureReq": {
        "CloseTradeCoinExposureReq": [
            {"name": "_trader", "type": "address"},
            {"name": "_pairIndex", "type": "uint256"},
            {"name": "_index", "type": "uint256"},
            {"name": "_openTimestamp", "type": "uint256"},
            {"name": "_coinExposure", "type": "uint256"},
            {"name": "_wantedPrice", "type": "uint256"},
            {"name": "_deadline", "type": "uint256"},
            {"name": "_nonce", "type": "uint256"},
        ],
    },
    "IncreasePositionSizeReq": {
        "IncreasePositionSizeReq": [
            {"name": "_updateInfo", "type": "UpdatePositionSize"},
            {"name": "_slippageP", "type": "uint256"},
            {"name": "_deadline", "type": "uint256"},
            {"name": "_nonce", "type": "uint256"},
        ],
        "UpdatePositionSize": _UPDATE_POSITION_SIZE_TYPE,
    },
    "IncreasePositionSizeWithCoinExposureReq": {
        "IncreasePositionSizeWithCoinExposureReq": [
            {"name": "_updateInfo", "type": "UpdatePositionSize"},
            {"name": "_coinExposure", "type": "uint256"},
            {"name": "_minLeverage", "type": "uint256"},
            {"name": "_maxLeverage", "type": "uint256"},
            {"name": "_slippageP", "type": "uint256"},
            {"name": "_deadline", "type": "uint256"},
            {"name": "_nonce", "type": "uint256"},
        ],
        "UpdatePositionSize": _UPDATE_POSITION_SIZE_TYPE,
    },
    # NB: `trader` is unprefixed while every other field is `_`-prefixed.
    "UpdateTpSlReq": {
        "UpdateTpSlReq": [
            {"name": "trader", "type": "address"},
            {"name": "_pairIndex", "type": "uint256"},
            {"name": "_index", "type": "uint256"},
            {"name": "_newTp", "type": "uint256"},
            {"name": "_newSl", "type": "uint256"},
            {"name": "_deadline", "type": "uint256"},
            {"name": "_nonce", "type": "uint256"},
        ],
    },
    # No deadline field — freshness enforced via `signTimestamp` (ms).
    "TpSlReq": {
        "TpSlReq": [
            {"name": "trader", "type": "address"},
            {"name": "pairIndex", "type": "uint256"},
            {"name": "index", "type": "uint256"},
            {"name": "triggerType", "type": "uint8"},
            {"name": "coinSize", "type": "uint256"},
            {"name": "buy", "type": "bool"},
            {"name": "price", "type": "uint256"},
            {"name": "percentage", "type": "int256"},
            {"name": "timestamp", "type": "uint256"},
            {"name": "signTimestamp", "type": "uint256"},
            {"name": "orderType", "type": "uint8"},
            {"name": "nonce", "type": "uint256"},
        ],
    },
    "TwapOpenOrder": {
        "TwapOpenOrder": [
            {"name": "trader", "type": "address"},
            {"name": "pairIndex", "type": "uint256"},
            {"name": "collateral", "type": "uint256"},
            {"name": "buy", "type": "bool"},
            {"name": "isCoin", "type": "bool"},
            {"name": "coinSize", "type": "uint256"},
            {"name": "defaultLeverage", "type": "uint256"},
            {"name": "maxLeverage", "type": "uint256"},
            {"name": "runTime", "type": "uint256"},
            {"name": "nonce", "type": "uint256"},
            {"name": "deadline", "type": "uint256"},
            {"name": "__reserved1", "type": "uint256"},
        ],
    },
    "TwapCloseOrder": {
        "TwapCloseOrder": [
            {"name": "trader", "type": "address"},
            {"name": "pairIndex", "type": "uint256"},
            {"name": "index", "type": "uint256"},
            {"name": "coinSizeToClose", "type": "uint256"},
            {"name": "runTime", "type": "uint256"},
            {"name": "nonce", "type": "uint256"},
            {"name": "deadline", "type": "uint256"},
            {"name": "__reserved1", "type": "uint256"},
        ],
    },
    "RfqOpenOrder": {
        "RfqOpenOrder": [
            {"name": "trader", "type": "address"},
            {"name": "pairIndex", "type": "uint256"},
            {"name": "collateral", "type": "uint256"},
            {"name": "buy", "type": "bool"},
            {"name": "isCoin", "type": "bool"},
            {"name": "coinSize", "type": "uint256"},
            {"name": "defaultLeverage", "type": "uint256"},
            {"name": "maxLeverage", "type": "uint256"},
            {"name": "wantedPrice", "type": "uint256"},
            {"name": "maxSlippageP", "type": "uint256"},
            {"name": "nonce", "type": "uint256"},
            {"name": "deadline", "type": "uint256"},
        ],
    },
    "RfqCloseOrder": {
        "RfqCloseOrder": [
            {"name": "trader", "type": "address"},
            {"name": "pairIndex", "type": "uint256"},
            {"name": "index", "type": "uint256"},
            {"name": "coinSizeToClose", "type": "uint256"},
            {"name": "wantedPrice", "type": "uint256"},
            {"name": "maxSlippageP", "type": "uint256"},
            {"name": "nonce", "type": "uint256"},
            {"name": "deadline", "type": "uint256"},
        ],
    },
    # Typehash order (expiry, deadline, tnc) differs from the Solidity struct
    # declaration (expiry, tnc, deadline); typed data follows the typehash.
    "DelegateReq": {
        "DelegateReq": [
            {"name": "trader", "type": "address"},
            {"name": "delegate", "type": "address"},
            {"name": "expiry", "type": "uint256"},
            {"name": "deadline", "type": "uint256"},
            {"name": "tnc", "type": "string"},
            {"name": "nonce", "type": "uint256"},
        ],
    },
    "RegisterCodeReq": {
        "RegisterCodeReq": [
            {"name": "_code", "type": "bytes32"},
            {"name": "_referrer", "type": "address"},
            {"name": "_deadline", "type": "uint256"},
            {"name": "_nonce", "type": "uint256"},
        ],
    },
    "SetTraderReferralCodeByUserReq": {
        "SetTraderReferralCodeByUserReq": [
            {"name": "_code", "type": "bytes32"},
            {"name": "_referee", "type": "address"},
            {"name": "_deadline", "type": "uint256"},
            {"name": "_nonce", "type": "uint256"},
        ],
    },
}

REFERRAL_INTENTS = {"RegisterCodeReq", "SetTraderReferralCodeByUserReq"}


def trading_domain(chain_id: int, trading_router: str) -> dict:
    return {
        "name": "AvantisTrading",
        "version": "1",
        "chainId": chain_id,
        "verifyingContract": trading_router,
    }


def referral_domain(chain_id: int, referral: str) -> dict:
    return {
        "name": "AvantisTrading",
        "version": "1",
        "chainId": chain_id,
        "verifyingContract": referral,
    }
