"""EIP-7702/Gelato encoder parity: reproduce the REAL @gelatocloud/gasless
``encodeCallData`` output byte-for-byte, plus the EIP-7702 authorization.

Reference payload generated by tests/vectors/gen_eip7702_reference.mjs using
the actual Gelato SDK from avantis-ui-v2's node_modules.
"""

import json
from pathlib import Path

from avantis_trader_sdk_v2.eip7702 import Call, GelatoDelegationEncoder, encode_nonce
from avantis_trader_sdk_v2.eip7702.account import delegation_code
from avantis_trader_sdk_v2.signing import LocalSigner

REF = json.loads((Path(__file__).parent / "vectors" / "eip7702_reference.json").read_text())


def _encoder() -> GelatoDelegationEncoder:
    return GelatoDelegationEncoder(
        signer=LocalSigner(REF["privateKey"]),
        chain_id=REF["chainId"],
        delegation_address=REF["authorization"]["address"],
    )


def _calls() -> list[Call]:
    return [Call.from_hex(c["to"], c["data"], int(c["value"])) for c in REF["calls"]]


def test_encode_call_data_matches_gelato_sdk():
    data = _encoder().encode_call_data(_calls(), int(REF["nonce"]))
    assert "0x" + data.hex() == REF["encodeCallData"].lower()


def test_authorization_matches_viem():
    auth = _encoder().authorization(account_nonce=REF["authorization"]["nonce"])
    assert auth["address"] == REF["authorization"]["address"]
    assert auth["r"] == REF["authorization"]["r"]
    assert auth["s"] == REF["authorization"]["s"]
    assert auth["yParity"] == REF["authorization"]["yParity"]


def test_build_type4_shape():
    type4 = _encoder().build_type4(
        _calls(), gas=1_000_000, account_nonce=0, exec_nonce=int(REF["nonce"])
    )
    # blitz-relayer TxParamsDto: numeric chainId, gasLimit string, type 4
    assert type4["chainId"] == REF["chainId"]
    assert type4["to"] == REF["owner"]
    assert type4["gasLimit"] == "1000000"
    assert type4["transactionType"] == 4
    assert type4["value"] == "0"
    assert type4["data"] == REF["encodeCallData"].lower()
    (auth,) = type4["authorizationList"]
    assert auth["chainId"] == REF["chainId"]
    assert auth["nonce"] == 0
    assert auth["yParity"] == REF["authorization"]["yParity"]
    assert auth["v"] == auth["yParity"] + 27


def test_builder_code_suffix_appended():
    enc = _encoder()
    enc.builder_code = "0x" + "ab" * 32
    data = enc.encode_call_data(_calls(), int(REF["nonce"]))
    assert data.hex().endswith("ab" * 32)
    assert "0x" + data[:-32].hex() == REF["encodeCallData"].lower()


def test_encode_nonce_scheme():
    assert encode_nonce(5, 7) == (5 << 64) | 7
    assert int(REF["nonce"]) >> 64 == 1234567890123


def test_delegation_code():
    assert (
        delegation_code("0x5aF42746a8Af42d8a4708dF238C53F1F71abF0E0")
        == "0xef01005af42746a8af42d8a4708df238c53f1f71abf0e0"
    )
