"""Golden-vector suite: prove the SDK's EIP-712 signing reproduces the exact
digests computed by the real on-chain SignatureHelpers library.

Vectors come from avantis-tx-builder/tests/golden-vectors/vectors.json
(generated by executing the compiled contracts on anvil). If these pass, the
signer handles every quirk: millisecond deadlines, mixed `_`-prefix field
names, the deadline-less TpSlReq with a negative int256, and the DelegateReq
ToS constant.
"""

import json
from pathlib import Path

import pytest
from eth_account import Account

from avantis_trader_sdk_v2.errors import DigestMismatchError
from avantis_trader_sdk_v2.intents_schema import INTENT_TYPES
from avantis_trader_sdk_v2.signing import LocalSigner, sign_intent
from avantis_trader_sdk_v2.types import IntentPayload

VECTORS = json.loads((Path(__file__).parent / "vectors" / "vectors.json").read_text())

# well-known anvil test key — test-only
TEST_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"


def _payload_for(vector: dict) -> IntentPayload:
    kind = vector["kind"]
    return IntentPayload.model_validate(
        {
            "intent": kind,
            "signerRule": "trader-only" if kind == "DelegateReq" else "trader-or-delegate",
            "domain": VECTORS["domain"],
            "primaryType": kind,
            "types": INTENT_TYPES[kind],
            "message": vector["message"],
            "digest": vector["digest"],
            "encodedIntent": "0x",
        }
    )


@pytest.mark.parametrize("vector", VECTORS["vectors"], ids=lambda v: v["kind"])
def test_digest_matches_onchain_library(vector):
    signer = LocalSigner(TEST_KEY)
    signed = sign_intent(_payload_for(vector), signer)

    # signature is 65-byte r||s||v and recovers to the signer
    sig = bytes.fromhex(signed.signature[2:])
    assert len(sig) == 65
    assert sig[64] in (27, 28)
    recovered = Account._recover_hash(vector["digest"], signature=sig)
    assert recovered.lower() == signer.address.lower()


def test_digest_mismatch_is_fatal():
    vector = dict(VECTORS["vectors"][0])
    payload = _payload_for(vector)
    payload.digest = "0x" + "00" * 32
    with pytest.raises(DigestMismatchError):
        sign_intent(payload, LocalSigner(TEST_KEY))


def test_all_15_intent_kinds_covered():
    kinds = {v["kind"] for v in VECTORS["vectors"]}
    assert kinds == set(INTENT_TYPES.keys())
    assert len(kinds) == 15
